#!/usr/bin/env bash

folder="$HOME/Music/mpd"
script_folder="$HOME/Music/utils"
valid_tags="genre date albumartist tracknumber title"

# NOTE: album names with " - " may break

change_tags () { \
    track="$1"
    tag="$2"

    # list curr tag
    show_tags=$(uv run "$script_folder/get_tag_track.py" "$track" "--$tag")

    only_track=$(echo $album | awk -F/ '{print $3}')
    input=$(printf "$show_tags" | dmenu -i -c -l 1 -p "$only_track ($tag): ")
    [ -z "$input" ] && notify-send "Metadata change canceled" "\'$tag\' not changed" && exit 0

    uv run "$script_folder/set_tag_track.py" "$track" "--$tag" "$input" \
        && notify-send "Changed track metadata"
}

selected () { \
    album=$(
        find $folder -mindepth 2 -maxdepth 2 -type d -printf "%P\n" \
        | awk -F/ '{print $2}' \
        | sort -df \
        | dmenu -i -c -l 5 -p "Album: ")
    [ -z "$album" ] && exit 0
    album_path=$(find $folder -mindepth 2 -maxdepth 2 -type d -printf "%P\n" \
        | grep "$album")

    track=$(find "$folder/$album_path" -mindepth 1 -maxdepth 1 -type f \( -name "*.flac" -o -name "*.mp3" -o -name "*.ogg" -o -name "*.wav" \) -printf "%P\n" \
        | sort -df \
        | dmenu -i -c -l 5 -p "Track: ")
    [ -z "$track" ] && exit 0

    tag=$(printf "$valid_tags" \
        | tr ' ' '\n' \
        | dmenu -c -l 5 -sb "#9ece6a" -p "What tag to edit? ")
    [ -z "$tag" ] && exit 0
    if [[ "$valid_tags" == *"$tag"* && "$tag" != *" "* ]]; then
        change_tags "$album_path/$track" "$tag"
    else
        exit 1
    fi
}

selected

